config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
   resources :comments
  end

root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
 belongs_to :user
 has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
  @post = Post.find(params[:post_id])
  @comment = @post.comments.create(params[:comment].permit(:comment))
  @comment.user_id = current_user.id if current_user
  @comment.save

  if @comment.save
   redirect_to post_path(@post)
  else
   render 'new'
  end
 end

 def edit
  @post = Post.find(params[:post_id])
  @comment = @post.comments.find(params[:id])
 end

 def update
  @post = Post.find(params[:post_id])
  @comment = @post.comments.find(params[:id])

  if @comment.update(params[:comment].permit(:comment))
   redirect_to post_path(@post)
  else
   render 'edit'
  end
 end

 def destroy
  @post = Post.find(params[:post_id])
  @comment = @post.comments.find(params[:id])
  @comment.destroy
  redirect_to post_path(@post)
 end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :find_post, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, except: [:index, :show]

 def index
  @posts = Post.all.order("created_at DESC")
 end

 def new
  @post = current_user.posts.build
 end

 def create
   @post = current_user.posts.build(post_params)

 if @post.save
    redirect_to @post
   else
    render 'new'
   end
  end

 def show
 end

 def edit
 end

 def update
  if @post.update(post_params)
   redirect_to @post
  else
   render 'edit'
  end
 end

 def destroy
  @post.destroy
  redirect_to root_path
 end

def find_post
    @post = Post.find(params[:id])
end

private

 def post_params
  params.require(:post).permit(:title, :content)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
%p.comment_content= comment.comment
%p.comment_author= comment.user.email

- if user_signed_in?
   = link_to "Editar", edit_post_comment_path(comment.post, comment)
   = link_to "Deletar", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
 = f.input :comment
 = f.submit

app/views/comments/edit.html.haml
%h1 Editar resposta

:javascript
    tinymce.init({ selector:'textarea' });

= simple_form_for([@post, @comment]) do |f|
    = f.input :comment
    = f.submit

app/views/layouts/application.html.haml
!!!
%html
%head
  %title NUTED Forum
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag "jquery-3.3.1.min"
  = csrf_meta_tags
%body
  %header
    %p= link_to "NUTED Forum", root_path
    - if user_signed_in?
      = link_to "Novo Tópico", new_post_path
      = link_to "Logout", destroy_user_session_path
    - else
      = link_to "Registrar", new_user_registration_path
      = link_to "Login", new_user_session_path

.wrapper
  %p.notice= notice
  %p.alert= alert

.wrapper
  = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  = f.submit

app/views/posts/edit.html.haml
:javascript
    tinymce.init({ selector:'textarea' });

%h1 Edit post

= render 'form'

= link_to "Cancelar", post_path

app/views/posts/index.html.haml
%h1 Tópicos

- @posts.each do |post|
 %h2= link_to post.title, post

 %p
 = post.comments.count
 comentários

 %p
 Publicado há
 = time_ago_in_words(post.created_at)
 = post.user.email

app/views/posts/new.html.haml
:javascript
    tinymce.init({ selector:'textarea' });

%h1 Novo tópico

= render 'form'

app/views/posts/show.html.haml
%h1= @post.title
%p= @post.content

%p
= @post.comments.count
comentários

= render @post.comments

- if user_signed_in?
   %h3 Responder
   = render "comments/form"